name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            # kill existing process if it exists
            tmux kill-session -t snake-game || true

            cd /root/snake-game
            git pull origin main --no-rebase
            bun install
            bun run build:client

            tmux new-session -d -s snake-game "bun start 2>&1 | tee /root/snake.log"