name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container:
      image: oven-sh/bun:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: bun install
      - name: Run lint
        run: bun run ci:lint

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: oven-sh/bun:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: bun ci
      - name: Run tests
        run: bun run ci:test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    container:
      image: oven-sh/bun:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: bun install
      - name: Run build
        run: bun run ci:build

  format:
    name: Assert code formatting
    runs-on: ubuntu-latest
    container:
      image: oven-sh/bun:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: bun install
      - name: Run format check
        run: bun run ci:format